export const FETCH_STUDENTS="FETCH_STUDENTS";
export const FETCH_STUDENTS_SUCCESS="FETCH_STUDENTS_SUCCESS";
export const FETCH_STUDENTS_FAILURE="FETCH_STUDENTS_FAILURE";

export const ADD_STUDENT="ADD_STUDENT";
export const ADD_STUDENT_SUCCESS="ADD_STUDENT_SUCCESS";
export const ADD_STUDENT_FAILURE="ADD_STUDENT_FAILURE";